### ISSUE TITLE
Cant' get it to work with Browserify

### ISSUE THREAD

**Issue by pdechery** [jasondavies/d3-cloud#100]
Hi,

I'm struggling to get this nice plugin to work with my app.

I've installed it with npm and My browserify dependencies are set up like so:
```
jQuery = require('jquery')
require('../vendor/jquery.fullpage.min')

require('perfect-scrollbar/jquery')(jQuery)

global.d3 = require('../vendor/d3')

d3tip_module = require('d3-tip')
d3tip_module(d3)

d3cloud_module = require('d3-cloud')
d3cloud_module(d3)

```
When I run nothing appears and I get a 'd3.layout.cloud is not a function' in console.

Any help would be much appreciated.

Pierre

**Comment by jasondavies** [comment]
I’m not sure why you are initialising it using `d3cloud_module(d3)` (and presumably later with `d3.layout.cloud`, perhaps you should start with the sample in `examples/browserify.js`?  Using `d3.layout.cloud` is the non-browserify way of doing things; with browserify it’s a standalone module.

**Comment by pdechery** [comment]
Hi Jason, thank you. 

I didn't see the examples but now it makes sense to me and it's working!

http://dapp.fgv.br/esportes/olimpiadas-2016/#ferramenta/time-brasil-vis
