### ISSUE TITLE
word cloud with clickable links or adding click events

### ISSUE THREAD

**Issue by maurod69** [jasondavies/d3-cloud#101]
Does the API support anchor tags to make the words clickable? furthermore, is there a way to add attributes to send functions or events?

**Comment by jasondavies** [comment]
This library deals with positioning/layout only; event-handling and rendering can be done using D3 or other libraries.

**Comment by maurod69** [comment]
thanks I found the way and it was pretty simple.

**Comment by kartikgill** [comment]
@maurod69 can you please help me making adding clickable events to tag cloud?

**Comment by owendall** [comment]
@maurod69 Can you share what you did for the click event?

**Comment by Honghe** [comment]
@owendall With element click event, we can show the related info of the item.

**Comment by jicihome** [comment]
Can you explain what you add or do to make it work?
Thanks! @maurod69 @Honghe
