### ISSUE TITLE
Will this be updated for v4?

### ISSUE THREAD

**Issue by emeeks** [jasondavies/d3-cloud#107]
I describe this layout in one of the chapters of my book and I'm updating that to the 2nd edition for d3v4 and I was wondering if there will be a v4 version of this chart forthcoming. If not, no worries, I can replace the word cloud section with something else.

**Comment by jasondavies** [comment]
What do you mean by “v4 version”?

**Comment by aknuds1** [comment]
@jasondavies He means the D3 v4 API

**Comment by jasondavies** [comment]
This library has a single dependency, [d3-dispatch](https://www.npmjs.com/package/d3-dispatch), so I don’t think anything needs to be done for D3 v4 compatibility.  If you think something *does* need to be done, please reopen and provide details.

**Comment by aknuds1** [comment]
@jasondavies Maybe you should have a look at the [v4 PR](https://github.com/jasondavies/d3-cloud/pull/109) and voice your opinion?

**Comment by feifang** [comment]
It still works with D3 v4 :) 
Most code examples online fails because of the error: `d3.layout.cloud() is not a function`. I encountered the same error while using d3-cloud in my Vue app, but eventually solved it (inspired by the [d3-cloud examples](https://github.com/jasondavies/d3-cloud/tree/master/examples)):
```
import * as cloud from 'd3-cloud'
// ...
// instead of using d3.layout.cloud()
var layout = cloud()
              .size([width, height])
              .words(words)
// ...
```

**Comment by gustavz** [comment]
> It still works with D3 v4 :)
> Most code examples online fails because of the error: `d3.layout.cloud() is not a function`. I encountered the same error while using d3-cloud in my Vue app, but eventually solved it (inspired by the [d3-cloud examples](https://github.com/jasondavies/d3-cloud/tree/master/examples)):
> 
> ```
> import * as cloud from 'd3-cloud'
> // ...
> // instead of using d3.layout.cloud()
> var layout = cloud()
>               .size([width, height])
>               .words(words)
> // ...
> ```

How is this supposed to work?

**Comment by RudyBai** [comment]
Hey all, I have the same issue with creating a wordcloud in React using raw D3v4 by accessing an svg ref using a hook.
Using the snippet previously mentioned yields
```
This expression is not callable.
  Type '{ default: { (): Cloud<Word>; <T extends Word>(): Cloud<T>; }; }' has no call signatures.  TS2349
```

**Comment by RudyBai** [comment]
Nevermind! Using `import cloud from "d3-cloud";` instead works! `import * as cloud from 'd3-cloud'` wouldn't.
