### ISSUE TITLE
Word Cloud Generator eats hyphen and other punctuation symbols from text line

### ISSUE THREAD

**Issue by MurzNN** [jasondavies/d3-cloud#117]
If I select "One word per line" - it eats hyphen and most of punctuation symbols of http://i.imgur.com/hTD3FZp.png 
Text is
```
Test-1 string
Test--2
Test:3
Test/4
Test+5
Test - long -- string
Test.dot
Test,test2
```
How we can fix this problem?

**Comment by jasondavies** [comment]
Thanks for the report.  I’ve turned off punctuation removal when "one word per line" is selected.
