### ISSUE TITLE
Issues using RequireJS to load D3 and Word Cloud Layout

### ISSUE THREAD

**Issue by UncleZen** [jasondavies/d3-cloud#121]
Hi @jasondavies 

I am trying to run some of the examples you have provided. However, instead of downloading the D3.js and d3.layout.cloud.js scripts directly in the page, I am trying to load them via RequireJS. 

I have also posted a question on SO, so please check this question for further details: http://stackoverflow.com/questions/43769099/using-requirejs-to-load-d3-and-word-cloud-layout. 

Any help would be greatly appreciated.

Thanks!

Zen

**Comment by jasondavies** [comment]
Answered on SO.

**Comment by UncleZen** [comment]
Thanks Jason!
