### ISSUE TITLE
Can we make this svg cloud responsive

### ISSUE THREAD

**Issue by jithinsayone** [jasondavies/d3-cloud#122]

**Comment by plonknimbuzz** [comment]
just change your old width/height with your new width/heigth container when window event resize trigerred. 

or you can try this : https://julienrenaux.fr/2014/09/23/d3-js-responsive-word-cloud/

**Comment by daverted** [comment]
The SVG can be made responsive by defining the viewBox attribute and styling width and height. See PR #128 for an example.
