### ISSUE TITLE
Quote-Unquote!

### ISSUE THREAD

**Issue by pgoswami3** [jasondavies/d3-cloud#123]
Hi Jason,

I know it's not a real issue but any help would be appreciated.

I'm trying to render my tweets into a word cloud but when I project my array of words, the array of quoted texts turns out to be unquoted one.

The only change on your part of code is to use my variable (textOnly)

```
d3.layout.cloud().size([600, 600])
        .words(<%= textOnly %>.map(function(d) {
          return {text: d, size: 10 + Math.random() * 90};
}))

```
, instead of an array of predefined words ['I', 'am', 'Groot']

Snap 1: Console o/p with quoted/unique words
<img width="886" alt="screen shot 2017-05-29 at 10 26 44 am" src="https://cloud.githubusercontent.com/assets/10457560/26557876/744d315e-4459-11e7-9469-d6cc7facb8a7.png">

Snap 2: o/p in browser
<img width="911" alt="screen shot 2017-05-29 at 10 27 16 am" src="https://cloud.githubusercontent.com/assets/10457560/26557877/744f8274-4459-11e7-8bb3-96fea3e4ba31.png">

**Comment by jasondavies** [comment]
Looks like you aren't encoding your variable correctly as a JavaScript array in your JSP template.  (I assume that's JSP syntax.)  Sorry, this isn't the place to ask for generic help: try [StackOverflow](https://stackoverflow.com/).
