### ISSUE TITLE
words doesn't show up, goes into infinite loop when integrated in an iPhone app and tested on ipod touch. 

### ISSUE THREAD

**Issue by mafazr** [jasondavies/d3-cloud#13]
It does show up without an order (words overlapped totally- unreadable) only when the following function is commented out:

 function place(board, tag, bounds) {
     var perimeter = [{x: 0, y: 0}, {x: size[0], y: size[1]}],
         startX = tag.x,
         startY = tag.y,
         maxDelta = Math.sqrt(size[0] \* size[0] + size[1] \* size[1]),
         s = spiral(size),
         dt = Math.random() < .5 ? 1 : -1,
         t = -dt,
         dxdy,
         dx,
         dy;

```
 while (dxdy = s(t += dt)) {
   dx = ~~dxdy[0];
   dy = ~~dxdy[1];

   if (Math.min(dx, dy) > maxDelta) break;

   tag.x = startX + dx;
   tag.y = startY + dy;

   if (tag.x + tag.x0 < 0 || tag.y + tag.y0 < 0 ||
       tag.x + tag.x1 > size[0] || tag.y + tag.y1 > size[1]) continue;
   // TODO only check for collisions within current bounds.
   if (!bounds || !cloudCollide(tag, board, size[0])) {
     if (!bounds || collideRects(tag, bounds)) {
      var sprite = tag.sprite,
           w = tag.width >> 5,
           sw = size[0] >> 5,
           lx = tag.x - (w << 4),
           sx = lx & 0x7f,
           msx = 32 - sx,
           h = tag.y1 - tag.y0,
           x = (tag.y + tag.y0) * sw + (lx >> 5),
           last;
       for (var j = 0; j < h; j++) {
         last = 0;
         for (var i = 0; i <= w; i++) {
           board[x + i] |= (last << msx) | (i < w ? (last = sprite[j * w + i]) >>> sx : 0);
         }
         x += sw;
       }
       delete tag.sprite;
       return true;
     }
   }
 }
 return false;
```

   }

**Comment by jkristoffer** [comment]
I encountered a similar issue whereby the `place` function goes into an infinite loop.
I have a SPA, one of my views contains a WordCloud instance. If I allow the WordCloud to finish loading it works just fine. However, if I navigate away from the view before the WordCloud finishes rendering, it goes into an infinite loop and crashes the browser.
