### ISSUE TITLE
Collision 

### ISSUE THREAD

**Issue by injoum** [jasondavies/d3-cloud#130]
I am still having issues on how to make the wordcloud work without collisions, does that work?

**Comment by injoum** [comment]
var fill = d3.scale.category20();
    
    var layout = d3.layout.cloud().size([1000, 1000])
            .words(frequency_list)
            .padding(true)
            .rotate(0)
            .text(function(d){debugger; return d.text})
            .font("sans-serif")
            .fontSize(function(d) { return d.size; })
            .on("end", draw);
            layout.start();

function draw(words) {
        d3.select("body").append("svg")
                .attr("width",layout.size()[0])
                .attr("height", layout.size()[1])
                .attr("class", "legend")
                .append("g")
                // without the transform, words words would get cutoff to the left and top, they would
                // appear outside of the SVG area
                .attr("transform", "translate(" + layout.size()[0] / 2 + "," + layout.size()[1] / 2 + ")")
                .selectAll("text")
                .data(words)
                .enter().append("text")
                .style("font-size", function (d) { return d.size + "px"; })
                .style("fill", function (d, i) { return fill(i); })
                .attr("transform", function(d) {
                    return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
                })
                .text(function(d) { return d.text; });
    }

![image](https://user-images.githubusercontent.com/10351706/29065213-a9931856-7c2b-11e7-9d9d-f78cb3c8e8b6.png)

**Comment by jasondavies** [comment]
You are missing `.attr("text-anchor", "middle")`.

**Comment by injoum** [comment]
Thank you this helped me get around the edges the words were being cut off but still some words are not readable due to collision:

![image](https://user-images.githubusercontent.com/10351706/29069445-4fb68ab0-7c3b-11e7-8060-6cf47897d836.png)

**Comment by jasondavies** [comment]
Please post a reproducible example.  I also noticed that you needed to add `.attr("font-family", …)` to ensure the same font is used by the layout algorithm and your "draw" function.

**Comment by jasondavies** [comment]
(You can use <https://jsfiddle.net> or <https://bl.ocks.org>.)

**Comment by injoum** [comment]
https://jsfiddle.net/84gonu1o/#&togetherjs=caqHNTPIII

**Comment by jasondavies** [comment]
You didn't add `.attr("text-anchor", "middle")` to the correct place; it needs to be added to each `<text>` element.  See [the bundled example here](https://github.com/jasondavies/d3-cloud/blob/f00a511341fb4c9d9fce2faacea212687d653915/examples/browserify.js#L33).

**Comment by injoum** [comment]
same output

**Comment by injoum** [comment]
https://jsfiddle.net/au4nhL96/

**Comment by jasondavies** [comment]
Can you post an example that actually runs (full code, HTML etc.)?  If you ask for help, make it as easy as possible for someone to help you, otherwise they end up spending most of their time trying to reproduce it…

**Comment by injoum** [comment]
oh am really sorry I didn't mean to, it is just I am not working with a normal html page I am creating it in an Oracle APEX plugin so am recreating it in an html page now at the moment so we can see what is wrong

**Comment by injoum** [comment]
`<!DOCTYPE html>
         <head>
         <script src="cloud.js"></script>
         <script src="d3.layout.cloud.js"></script>
         </head>
         <style>
          body {
        font-family:"Lucida Grande","Droid Sans",Arial,Helvetica,sans-serif;
    }
    .legend {
        border: 1px solid #555555;
        border-radius: 5px 5px 5px 5px;
        font-size: 0.8em;
        margin: 10px;
        padding: 8px;
    }
    .bld {
        font-weight: bold;
    }
        </style>
         <body>
         <p id="demo">
  50Hertz 0.60 ALPIQ (ATEL) 0.20 ALPIQ (EOS) 0.20 AMPRION 0.20 BEE 0.60 BEW 0.20 BGV 0.60 BMW 0.20 CKW 0.40 CURRENTA 0.20 DB KT smart 0.40 DREWAG 1.20 DREWAG eSales 0.40 E.ON edis 0.20 EEG 1.20 EGG 0.20 EHA 0.60 ENGIE (Electrabel) 0.20 ENSO 0.20 EPS 1.00
  ESB 3.60 ETE 0.60 EVN AT 0.20 EVN BG EP 0.80 EVO 0.20 EWE AG 0.60 EWE Netz 2.80 EWZ 1.60 EnBW 3.60 EnBW TNG (TransnetBW) 0.60 FHBER 0.80 FHM 0.80 FMV 0.20 GASAG EDM H V 0.60 GASAG Netz 2.40 INETZ 0.80 ISGE 0.20 KHR 0.40 Lichtblick 0.40 METRO 0.40 MITNETZ
  ecount 0.80 MVV 0.20 Mainova 0.20 NBBV 0.80 NETELEC 1.20 NGV 0.20 RWE (Westnetz) 11.40 SHLV 0.20 SK 0.60 SNH 0.80 SW Düsseldorf 3.00 SW Flensburg 0.40 SW Hannover 1.40 SW Kiel 0.20 SW Münster Netz 0.80 SW Münster Vertrieb 1.20 SWBW 0.40 SWISSGRID 0.80
  StWSN 0.20 StWW 0.40 TenneT 0.60 URBANA 0.20 VE Berlin 0.40 VE Sales 1.00 VNG ConCenS 0.20 VWS 1.20 Voltaris 1.20 WEMAG 1.60 WIHO 0.40 WINGAS 1.40 Wien Energie 1.00 ZEV 2.60 a.en 0.80
</p>
         
          </body>
          <script>
var string = document.getElementById("demo").innerHTML;
document.getElementById("demo").innerHTML="";

	function createFrequencyListFromText(text) {
		var result = [];
		var wordList = text.split(" ");
		var wordCount = {};
        var word = "";
		for (i in wordList) {
            
            if(isNaN(parseFloat(wordList[i]))){
			    word += wordList[i]+" ";
            }
            else{
			    wordCount[word] = wordList[i];
                word = "";
            }
			
		}
		for (word in wordCount) {
            var test = word.replace("&amp;","&");
			result.push({"text": test, "size": wordCount[word]*50}); 
		}
		return result;
	}

    
	var frequency_list = createFrequencyListFromText(string);
    
    var fill = d3.scale.category20();
    
    var layout = d3.layout.cloud().size([1000, 1000])
            .words(frequency_list)
            .padding(true)
            .rotate(function() { return ~~(Math.random() * 2) * 90; })
            .text(function(d){debugger; return d.text})
            .font("sans-serif")
            .fontSize(function(d) { return d.size; })
            .on("end", draw);
            layout.start();
    
    function draw(words) {
  d3.select("body").append("svg")
      .attr("width", layout.size()[0])
      .attr("height", layout.size()[1])
      .attr("class","legend")
    .append("g")
      .attr("transform", "translate(" + layout.size()[0] / 2 + "," + layout.size()[1] / 2 + ")")
    .selectAll("text")
      .data(words)
    .enter().append("text")
      .style("font-size", function(d) { return d.size + "px"; })
      .style("font-family", "sans-serif")
      .style("fill", function(d, i) { return fill(i); })
      .attr("text-anchor", "middle")
      .attr("transform", function(d) {
        return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
      })
      .text(function(d) { return d.text; });
}
</script>
          </html>
`

**Comment by jasondavies** [comment]
Sorry, but I've already asked you twice to post a working example that demonstrates the problem, and pasting incomplete code into the issue is clearly ignoring my request.

I normally have a rule that GitHub issues are for bug reports and feature requests only; **not** for asking for help.

I've already pointed out the main two issues that seem to trip people up: (a) text-anchor="middle" and (b) ensuring the same font is used for the layout and the output.

I'm afraid I don't have any more time or patience to continue with this GitHub issue, so please consider asking for help in another forum such as [StackOverflow](https://stackoverflow.com/questions/tagged/d3.js).
