### ISSUE TITLE
Firefox with Privacy Badger

### ISSUE THREAD

**Issue by ronnievdc** [jasondavies/d3-cloud#134]
Firefox browsers with Privacy Badget enabled crashes with the following error:
Exception  Error: ERROR.captureStackTrace is not a function

> Error: ERROR.captureStackTrace is not a function
getStackTrace@http://localhost:8000/:81:7
getOriginatingScriptUrl@http://localhost:8000/:96:19
trapInstanceMethod/item.obj[item.propName]</<@http://localhost:8000/:147:28
getContext@http://localhost:8000/plugins.js line 6 > eval:94:27
[1]</module.exports/cloud.start@http://localhost:8000/plugins.js line 6 > eval:37:27

This is because the Privacy Badger marks .getImageData() as fingerprinting. See the following comment: https://github.com/EFForg/privacybadger/issues/1418#issuecomment-311697454

**Comment by ghostwords** [comment]
Hi @ronnievdc, were you using Privacy Badger version 2017.9.12? This bug should have been fixed as of 2017.9.12.1. Sorry for the trouble!

**Comment by ronnievdc** [comment]
@ghostwords , Yes i was using Privacy Badger version 2017.9.12. With the 2017.9.12.1 update everything works fine. Thanks for the quick response.
