### ISSUE TITLE
Please update NPM

### ISSUE THREAD

**Issue by laredoza** [jasondavies/d3-cloud#135]
Hi,

Would it be possible to update https://www.npmjs.com/package/d3.layout.cloud.

Calling the events is out of date and is causing errors. Once I updated the index.js file(the latest from GITHUB) the npm worked properly.

Thanks

**Comment by jasondavies** [comment]
This package has been renamed to [d3-cloud](https://www.npmjs.com/package/d3-cloud).

**Comment by laredoza** [comment]
Thanks
