### ISSUE TITLE
Individual word padding/line-height removal?

### ISSUE THREAD

**Issue by b0gd4n** [jasondavies/d3-cloud#140]
Is there a way of removing/reducing the line-height or padding on the `text` elements?

![screen shot 2018-02-19 at 14 09 52](https://user-images.githubusercontent.com/1862528/36381999-658a887c-157f-11e8-96e4-a34145b8571c.png)

The reason behind this is that I have `mouseover` event listener on each word which increases the `font-size` for the hovered `text` element. The problem is then trying to hover off the element, but you are still on the transparent padding, and not hitting the item behind.

As you can see in the example above, it's nearly impossible to hit the smaller elements (`note`, `via`, etc.) around the bigger `words` element.

**Comment by jasondavies** [comment]
Sorry, these GitHub issues are for bug reports/feature requests only.  Please try [StackOverflow](https://stackoverflow.com/) if you need general help. But I'll give you a hint: you should be able to use SVG's [pointer-events](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events) to achieve what you want.

**Comment by b0gd4n** [comment]
I'm afraid nothing but `pointer-events: none` has any effect on this matter. In a way, this is a bug, as it add unnecessary padding on each `text` element. Just need to know how to remove that?

**Comment by jasondavies** [comment]
The d3-cloud library doesn't do any rendering at all; it just generates positions of words given their sizes such that the words do not overlap.  So any issues opened relating to SVG or other rendering problems are unfortunately out-of-scope here.

**Comment by b0gd4n** [comment]
@jasondavies ok - fair enough...
