### ISSUE TITLE
Is There a way to get consistent results for the largest contributors to the wordcloud

### ISSUE THREAD

**Issue by owendall** [jasondavies/d3-cloud#143]
See my post:

https://groups.google.com/forum/#!topic/vega-js/sG_5Bq6-z7w

**Comment by owendall** [comment]
![wordcloud-three-different-results](https://user-images.githubusercontent.com/10927/36758829-85d75654-1be3-11e8-888f-e3c41c972689.jpg)

**Comment by jasondavies** [comment]
You can override the random number generator using [cloud.random](https://github.com/jasondavies/d3-cloud#random) if you need consistent results (e.g. try a seeded RNG).

**Comment by owendall** [comment]
thanks for that, Jason. Will try that out.
