### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by xuhdev** [jasondavies/d3-cloud#145]
People often need a local tool for generating word cloud. It would be awesome if a CLI tool is built upon d3-cloud.

**Comment by adrianhelvik** [comment]
Use jsdom and save the string of the generated SVG.

**Comment by jasondavies** [comment]
You can use the example in `examples/node.js` using the [canvas](https://www.npmjs.com/package/canvas) package to generate word clouds without a browser.
