### ISSUE TITLE
Example not reproducible from bower install

### ISSUE THREAD

**Issue by yanickrochon** [jasondavies/d3-cloud#146]
In the example, there's this [line](https://github.com/jasondavies/d3-cloud/blob/master/examples/browserify.js#L4) :

```js
var fill = d3.scale.category20();
```

I'm looking all over the place, but this function `category20` is nowhere to be found in the bower packages.

**Comment by tfischer** [comment]
I ran into this problem as well.  From the changelog, this feature has been removed.  Instead, you can do something like this:

`var fill = d3.scaleOrdinal(d3.schemeAccent);`

See this for more options:
[https://github.com/d3/d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic)

**Comment by jasondavies** [comment]
Yes, the example was created in the days of D3 version 2.  D3 version 4 onwards split everything into smaller modules.  I removed the fill from the example to avoid any confusion.
