### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by kongmengfei** [jasondavies/d3-cloud#172]
how can  i use it in my project?  is there any document  to explain API  /props?

**Comment by Emporea** [comment]
This repo is so old it works only with older versions of d3. I just hope i can get it to work. I go through some error messages when trying.

**Comment by Emporea** [comment]
@kongmengfei 

Its actually pretty easy. I struggeled of just changing cloud to d3.layout.cloud in examples/browserify.js.
If you include your d3 cdn your are fine and can just use the code in browserify.js

If you  dont understand or have any further questions just let me know.

**Comment by superdiazzz** [comment]
> @kongmengfei
> 
> Its actually pretty easy. I struggeled of just changing cloud to d3.layout.cloud in examples/browserify.js. If you include your d3 cdn your are fine and can just use the code in browserify.js
> 
> If you dont understand or have any further questions just let me know.

i have tried change to this l`et layout = d3.layout.cloud()` but still unreadable. Btw, i use d3 by npm install

**Comment by jasondavies** [comment]
> This repo is so old it works only with older versions of d3. I just hope i can get it to work. I go through some error messages when trying.

This is simply not true: there's no requirement to use any specific version of D3 (or even D3 at all) -- this library simply generates sizes and positions for a given set of words.  There's a couple of examples in the repository but I may need to update them to reflect modern usage.
