### ISSUE TITLE
Unreadable under D3 V7

### ISSUE THREAD

**Issue by remember9069** [jasondavies/d3-cloud#179]
When i import this as `import * as d3 from 'd3'`, shows `Uncaught TypeError: Cannot read properties of undefined (reading 'cloud')` in console, in line where i call `cloud = d3.layout.cloud();`
And if i import this as `import * as cloud from "d3-cloud"`, it shows `Cannot find module 'd3-cloud' or its corresponding type declarations.`

**Comment by jasondavies** [comment]
Strictly speaking, you don't need D3 to use d3-cloud, although that's the most common scenario.  d3-cloud is a completely standalone module.  If you're using ESM you should be able to do:

```js
import d3_cloud from "d3-cloud";

const cloud = d3_cloud();
...
```

**Comment by remember9069** [comment]
> Strictly speaking, you don't need D3 to use d3-cloud, although that's the most common scenario. d3-cloud is a completely standalone module. If you're using ESM you should be able to do:
> 
> ```js
> import d3_cloud from "d3-cloud";
> 
> const cloud = d3_cloud();
> ...
> ```

Thank you very much for the quick and helpful reply.
After I did what you said, it appears
```
This expression is not callable.
  Type 'Cloud<Word>' has no call signatures.js(2349)
```
in this line 		`var layout = cloud()`

**Comment by jasondavies** [comment]
```js
var layout = d3_cloud()
```

**Comment by remember9069** [comment]
> ```js
> var layout = d3_cloud()
> ```

Yes, i found that mistake as well, thanks.
