### ISSUE TITLE
Using d3 from Latex

### ISSUE THREAD

**Issue by dedalozzo** [jasondavies/d3-cloud#181]
Is it possible to generate a word cloud calling d3 from LuaLaTex? I know it is possible to call a JavaScript function using the package `js`:

```
\usepackage{js}
```

Can I just copy the `d3.layout.cloud.js` in the tex project directory, and do something like this?

```
\documentclass{article}
\usepackage{filecontents}
\usepackage{svg}

\begin{filecontents*}{d3.layout.cloud.js}
% Contents of the `d3.layout.cloud.js` file here
\end{filecontents*}

\begin{document}

\begin{script}
  \input{d3.layout.cloud.js}
  \newcommand{\wordcloud}{\includesvg[width=\linewidth]{wordcloud.svg}}
  % Generate the word cloud
  \directlua{
    local cloud = createCloud("This is some sample text")
    local file = io.open("wordcloud.svg", "w")
    file:write(cloud)
    file:close()
  }
  % Insert the word cloud into the document
  \wordcloud
\end{script}

\end{document}
```

**Comment by jasondavies** [comment]
Sorry, I have no idea.  This sounds like a LuaTex question.  Maybe try StackOverflow?

**Comment by dedalozzo** [comment]
What I would to know is the minimum requirement to run the function. Forget about Latex. Let's suppose I have an embedded JavaScript engine, and I want to generate a word cloud, what file do I need to include and what function of the llibrary I need to execute? I can figure it out the rest.
