### ISSUE TITLE
Coloring words in the cloud

### ISSUE THREAD

**Issue by ghost** [jasondavies/d3-cloud#2]
Hi,

I want to know how to color differently each word in the cloud ?

Thanks for you help

Amine

**Comment by Honghe** [comment]
in d3 v4, use as follow:
```
var color = d3.scaleOrdinal(d3.schemeCategory10);
```

**Comment by alexresolute** [comment]
This no longer works. Is using custom style deprecated? At a skim, it almost looks like the textFill is hard coded to red...

**Comment by jankapunkt** [comment]
@alexresolute 

Looking at the example from the `/examples` folder I simply added this after the font family style:

```js
...
    .style('font-family', 'Impact')
    .style('fill', function (d) {
      return randomColor()
    })
...

// this is of course just an example, taken from 
// https://stackoverflow.com/a/25873123/3098783
const randomColor = () => {
  return 'hsla(' + (Math.random() * 360) + ', 100%, 50%, 1)';
}
```
