### ISSUE TITLE
Cannot get font() to work

### ISSUE THREAD

**Issue by vincenttheeten** [jasondavies/d3-cloud#3]
From the simple.html example

``` javascript
  ...
  d3.layout.cloud().size([300, 300])
      .words([
        "Hello", "world", "normally", "you", "want", "more", "words",
        "than", "this"].map(function(d) {
        return {text: d, size: 10 + Math.random() * 90};
      }))
      .rotate(function() { return ~~(Math.random() * 2) * 90; })
      .font('Impact')     // <!--------- DOESN'T WORK?
      .fontSize(function(d) { return d.size; })
      .on("end", draw)
      .start();
  ...
```

Can anyone advise how to fix it?

**Comment by Asimov4** [comment]
Can you elaborate what you mean by "You need to ensure you set the correct font-family for the resulting text (using CSS or similar)."?

**Comment by jasondavies** [comment]
The layout itself is output-agnostic: for a given set of words and configuration (font settings and so forth configured on the layout), the positions and sizes of the words are produced.  You then need to ensure that when rendering the words, you set the appropriate font along with the size.  If you’re using SVG, then you’ll probably use CSS.  You could also use canvas, in which case you would set the font on the canvas.

**Comment by Asimov4** [comment]
I see. Thanks for explaining that!
This example was also very helpful: http://jsfiddle.net/adiioo7/RUTpJ/light/

**Comment by jasondavies** [comment]
That’s essentially the same as the bundled d3-cloud [example](https://github.com/jasondavies/d3-cloud/blob/master/examples/simple.html). :)
