### ISSUE TITLE
Infinite loop if box size set to [0, 0]

### ISSUE THREAD

**Issue by danomatic** [jasondavies/d3-cloud#33]
Awesome project!

I just had a horrible time tracking down an infinite loop in this library.  I had a scenario where an async callback that draws the tag cloud sometimes fired after an element had been removed from the page.  It called .size([0,0]) and eventually .start(), which completely tanked the user's browser.

This is my solution, but perhaps .size() should reject the 0 values or throw an error:

      function step() {
        if (size[0] === 0 || size[1] === 0) {
            cloud.stop();
            event.end(tags, bounds);
            return;
        }

**Comment by JacquiManzi** [comment]
I have also encountered this problem and the above solution has worked for me. I would agree with .size() rejecting 0 values or throwing an error.
