### ISSUE TITLE
Overlap in wordcloud 

### ISSUE THREAD

**Issue by anbrun** [jasondavies/d3-cloud#38]
Hello! 

I am aware that there is already a solved post on a very similar issue, but the solution described there does not apply in my case.

When I try to use the wordcloud layout, I get frequent overlaps. 

For a test case I used the example code from this page with some slight changes and a file with some test words. I uploaded the files on Plunker: http://plnkr.co/edit/MfBFgG4dKCyW2gaNBkhf?p=preview

The overlaps do not happen every time, but fairly frequently when you do some reloads. I would really like to prevent that.

Other people reported the same issue and found that it was related to using web fonts or skipping the rotate parameter. This does not apply in my example.

I suspect that it might be related to the fact that there are to many words for the canvas size, however, I also did tests where I signficantly increased the canvas size and it still happened (though less frequently, as the random placement of the words made it less likely). In addition to that, you can see that several words are not shown at all due to the small canvas size. Why leave some out and create overlap for others? I'm pretty confused by this issue. Is there any mistake on my part?

**Comment by sujithasj** [comment]
Hi

I worked on this but still i'm getting overlapped words .Below is the Generated wordcloud
![d3wordcloud](https://cloud.githubusercontent.com/assets/25897866/24135646/06b71686-0e31-11e7-8079-e5e24d527b7f.png)

Below is my code
var color = d3.scale.linear()
            .domain([0,1,2,3,4,5,6,10,15,20,100])
            .range(["orange", "pink", "green", "red", "dark pink", "yellow", "pale yellow", "cyan", "orange", "blue", "brown", "#222"]);

    d3.layout.cloud().size([800, 300])
            .words(frequency_list)
			.padding(1)
            .rotate(function(d) { return 0; })
			.text(function(d) { return d.text; }) 
            .fontSize(function(d) { return d.size; })
            .on("end", draw)
            .start();

    function draw(words) {
        d3.select("body").append("svg")
                .attr("width", 850)
                .attr("height", 350)
                .attr("class", "wordcloud")
                .append("g")
                // without the transform, words words would get cutoff to the left and top, they would
                // appear outside of the SVG area
                .attr("transform", "translate(320,200)")
                .selectAll("text")
                .data(words)
                .enter().append("text")
                .style("font-size", function(d) { return d.size+10+ "px"; })
                .style("fill", function(d, i) { return color(i); })
                .attr("transform", function(d) {
                    return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
                })
                .text(function(d) { return d.text; })
				//.on("mousedown",console.log(this));
				.on("click", function(d) {	mouseoverlogic(d.text);});
    }

can u plz help me out

**Comment by sujithasj** [comment]
words are overlapping when i form wordcloud. which change i need to do in code can u please tell me. Its very important to me
