### ISSUE TITLE
No repeat words

### ISSUE THREAD

**Issue by Rongh1991** [jasondavies/d3-cloud#48]
Hi, is it possible to stop repeating words in the simple example? and also get the words from url instead a variable? thx for ur help

**Comment by jasondavies** [comment]
These are all things that can be achieved with a little JavaScript knowledge; I’m afraid I don’t have time to create a more in-depth tutorial but I would recommend reading more about [D3](http://d3js.org), e.g. try [d3.text](https://github.com/mbostock/d3/wiki/Requests#d3_text) for loading text data from a URL.
