### ISSUE TITLE
Add an option to limit the step function execution time

### ISSUE THREAD

**Issue by JacquiManzi** [jasondavies/d3-cloud#51]
Large data sets can cause the word cloud to spend a lot of time in the step function before drawing the final outcome. A maximum time limit option would be a nice addition.

I submitted a pull request with my own interpretation of this option.

**Comment by jasondavies** [comment]
Sorry about the lack of documentation, but I think `cloud.timeInterval` achieves a similar result, by limiting the amount of time spent in the step function.  Does that solve your issue?  Feel free to reopen if you think your approach is better!

**Comment by JacquiManzi** [comment]
Yes! That is exactly what I need, I will use cloud.timeInterval instead.

Thanks!
