### ISSUE TITLE
Resizing Issue

### ISSUE THREAD

**Issue by ardoramor** [jasondavies/d3-cloud#55]
When the canvas is resized, the words are redrawn but they overlap.

When the window resizes, I update svg canvas `width` and `height`. I also execute the following code:

```
this._canvas = d3.select(this._container)
	.append('svg')
	.attr('width', '100%')
	.attr('height', '100%');

this._cloud = this._canvas.append('g');

this._cloudLayout = d3.layout.cloud();
...
function update() {
   var $canvas = $(this._canvas.node()),
		canvasWidth = $canvas.width(),
		canvasHeight = $canvas.height();

   this._cloud.attr('transform', 'translate(' + (canvasWidth / 2) + ',' + (canvasHeight / 2) + ')');
   this._cloudLayout
		.stop()
		.size([canvasWidth, canvasHeight])
		.start();
}
```

The original layout upon refresh:

![image](https://cloud.githubusercontent.com/assets/6255652/7194416/d899ec04-e47c-11e4-82a3-1469d6437d28.png)

The layout after resizing of the window:

![image](https://cloud.githubusercontent.com/assets/6255652/7194426/fd8c01f0-e47c-11e4-92ed-3937ab23e993.png)

It also seems not to update the bounds somehow.

**Comment by jasondavies** [comment]
I think it would be helpful to see a full example demonstrating the issue.  Is it possible you aren’t updating the text positions properly?  Feel free to reopen if there is still a problem and you think there’s a bug, but I was unable to reproduce.

**Comment by StefanDimov** [comment]
I have the same problem, it occurs when a word is removed, because there wasn't a place for it to be placed, and then it re-enters, it seem to check if it's colliding / overlapping other words.
