### ISSUE TITLE
Real time update

### ISSUE THREAD

**Issue by geraldstanje** [jasondavies/d3-cloud#56]
Hi Jason,

thanks for the great example. I tried to extend it and want to add new words at runtime. Do you know why my approach slows down after about 150 words? I cant see any update after 150 words...

https://github.com/geraldstanje/realtime_wordcloud/blob/master/home.html

Thanks,
Gerald

**Comment by geraldstanje** [comment]
i tried this: http://jsfiddle.net/whwqn3by/
it stops updating after 150 words... any idea?

**Comment by jasondavies** [comment]
The algorithm will attempt to place each word, but it might not be possible due to lack of space, in which case the algorithm simply bails for that particular word and moves on to the next one.  I’d be interested in trying some possible workarounds in a future release.
