### ISSUE TITLE
Use multiple lines as one item

### ISSUE THREAD

**Issue by SkoricIT** [jasondavies/d3-cloud#58]
Is it possible to use multiple lines of text as one item? I need to display first name and last name with a line break in between. Any suggestions?

**Comment by jasondavies** [comment]
It’s not supported at the moment I’m afraid, but will keep this in mind for a future release.  Thanks.

**Comment by Ra1d3n** [comment]
Could you give me a few hints how I would go about adding this? I would send you a pull request if I manage to add it myself.
