### ISSUE TITLE
There is no simple way to specify color (fill) for a word

### ISSUE THREAD

**Issue by PhantomYdn** [jasondavies/d3-cloud#60]
It will be cool if "d" contains the same fields as original data: to have quick access to required additional things (like color and etc.).

**Comment by jasondavies** [comment]
Perhaps I’m missing something, but each word object is reused, so you should have access to any additional fields that you might have on your objects.

**Comment by PhantomYdn** [comment]
In my case it was fully new with just d3-cloud specific parameters,

**Comment by gaurav5430** [comment]
i am having the same issue, @PhantomYdn  were you able to resolve it?
