### ISSUE TITLE
If you define size[null, null] cloud hangs infinitely

### ISSUE THREAD

**Issue by cesine** [jasondavies/d3-cloud#67]
in a context where you specify the height and or width via variables, its possible they could be null (or negative for that matter).

What is the desired behavior, use the default size values? or throw an error? 

```javascript
cloud.size = function(_) {
      if (!arguments.length) return size;
      if (!_[0] || _[0] < 0) _[0] = DEFAULT_WIDTH;
      if (!_[1] || _[1] < 1) _[1] = DEFAULT_HEIGHT;
      return arguments.length ? (size = [+_[0], +_[1]], cloud) : size;
    };
```

**Comment by jasondavies** [comment]
Behaviour is undefined if the user doesn’t comply with the documented API.

**Comment by cesine** [comment]
k, so throw an error?

**Comment by jasondavies** [comment]
> throw an error?

I consider throwing errors defined behaviour.  Validating all configuration options and throwing errors makes the code longer and more complicated.  I appreciate that you might have a different opinion, but I prefer to keep the code short and simple.  The same philosophy regarding throwing errors applies to D3.

**Comment by cesine** [comment]
Yeah, I noticed that d3 has this kind of philosophy for compact javascript too, and I still like to use it  :)
