### ISSUE TITLE
Word collisions

### ISSUE THREAD

**Issue by voxlol** [jasondavies/d3-cloud#73]
I'm getting collisions when I try using D3- cloud. I've googled and looked at other issues with the similar problem, but their solution doesn't seem to work for me. 

I've attached a picture showing an example of the issue.

![pasted image at 2015_08_26 07_52 pm](https://cloud.githubusercontent.com/assets/11891171/9510028/1fc45a08-4c2c-11e5-9eee-7156b49a3165.png)

     module.keywordGraph = module.keywordGraph.map(function(keyObj){
          return {
            text: keyObj.name,
            size: keyObj.count,
            test: 'haha'
          };
        })

    d3.layout.cloud()
        .size([800, 500])
        .words(module.keywordGraph)
        .rotate(0)
        .text(function(d){debugger; return d.text})
        .fontSize(function(d) { return d.size; })
        .on("end", draw)
        .start();

      function draw(words) {
        var chart = d3.select("#graph-container").append('svg').attr("class", "wordcloud")
          .attr("height", 500)
          .attr("width", 800)
          .append("g")
          .attr('transform', 'translate(250,250)');

        chart.selectAll("text")
          .data(words)
            .enter().append("text")
            .style("font-size", function(d) { 
              return d.size + "px"; })
            .style("fill", function(d) { return colorScale(d.size); })
            .attr("transform", function(d) {
              return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
            })
            .text(function(d) {
              return d.text; });
            }

**Comment by jasondavies** [comment]
Usually this is caused by the layout and the SVG having different fonts.  Perhaps you need to set the font on the layout?
