### ISSUE TITLE
how to transition words to their next position as in the site

### ISSUE THREAD

**Issue by flyon** [jasondavies/d3-cloud#80]
I'm trying to animate the words to a new position after the word array changes.

I've seen this issue (https://github.com/jasondavies/d3-cloud/issues/12), and use the suggested code, but that still rerenders a complete new svg. 
I found [this example](http://bl.ocks.org/jwhitfieldseed/9697914) (which I got working by replacing the minified d3-cloud with the one in the build folder of this repo), and it has a nice animation. But it animates the words anew from the center every time.

Yet in the example on [the homepage of this repo](https://www.jasondavies.com/wordcloud/) the words are animated from their previous position. 

Could you please provide an example of how to do that? Or simply make the source code of that page more accesible?

since I'm not much familiar with d3 that would be very helpful.
tnx!

**Comment by vigel1990** [comment]
http://bl.ocks.org/jwhitfieldseed/9697914#index.html here
