### ISSUE TITLE
Word Cloud for Farsi String

### ISSUE THREAD

**Issue by hosseinGanjyar** [jasondavies/d3-cloud#86]
> My Question in Stackoverflow is [Here](http://stackoverflow.com/questions/35058827/jasondavies-word-cloud-for-farsi-string/35059757?noredirect=1#comment57921494_35059757)

I using [jasondavies](https://www.jasondavies.com/wordcloud/)'s Word Cloud for my project, but there is a problem that I using Persian[Farsi] Strings and my problem here that words have overlapping in Svg.
What happened to the Farsi words?
[Image](https://i.imgsafe.org/0a8cae10c6.png)

**Comment by huttarl** [comment]
I ran into the same problem. Presumably, the algorithm doesn't take right-to-left scripts into account. I wonder how hard this would be to fix.

**Comment by Detachment** [comment]
This problem also happens when using Chinese words, any solutions now?

**Comment by hosseinGanjyar** [comment]
@Detachment No solution... :(

**Comment by Harpush** [comment]
@jasondavies any news about that? Or is this not maintained anymore?

**Comment by jasondavies** [comment]
The algorithm shouldn't have any issues with RTL text in theory, but different browsers have exhibited bugs when handling RTL rendering in the past.  Even now, it seems Chrome exhibits an alignment bug when rendering RTL text to canvas.  I've resurrected this [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1010893).  In the meantime, I'll think about a possible workaround.

**Comment by jasondavies** [comment]
Not sure how the link you posted is relevant to this issue?

**Comment by Harpush** [comment]
> Not sure how the link you posted is relevant to this issue?

Might be wrong here but I didn't see the collision problem in this example. I am not very knowledgeable in canvas manipulation though so maybe the problem exists there too and comes from a different origin like the bug above mentioned.

**Comment by jasondavies** [comment]
> Might be wrong here but I didn't see the collision problem in this example. I am not very knowledgeable in canvas manipulation though so maybe the problem exists there too and comes from a different origin like the bug above mentioned.

The link you posted doesn't do text rendering.  I've found a workaround, but it may take me some time to publish the fix.

**Comment by hosseinGanjyar** [comment]
After around 7 years... Fixed!

Thanks @jasondavies
