### ISSUE TITLE
fontWeight is not a function

### ISSUE THREAD

**Issue by steve-nD** [jasondavies/d3-cloud#89]
I'm trying to adjust the fontWeight and I keep getting this error.  When I look at the d3.layout.cloud() object I do not see fontWeight included.

**Comment by jasondavies** [comment]
Insufficient information to reproduce.

**Comment by steve-nD** [comment]
Not sure what other information you need?  Here is a fiddle: https://jsfiddle.net/4netp2zu/

If you uncomment from d3.layout.cloud():

//.fontWeight(function(d) { return fontWeight(d.size) })

it doesn't display anything and in the console I get the following error: 

"Uncaught TypeError: d3.layout.cloud(...).words(...).size(...).rotate(...).font(...).fontSize(...).fontWeight is not a function"

Is this not the correct usage?

**Comment by jasondavies** [comment]
Your fiddle is linking to an ancient version.  Support for font weight was added over three years ago.
